name: Snake Game CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use NodeJS 20
      uses: actions/setup-node@v3
      with: 
        node-version: 20
    - run: |
        npm i
        npm run build:ocean
        rm -rf node_modules
